-- Path of Building
--
-- Module: Build Display Stats
-- Loads the displayStats and extraSaveStats.
--
-- This defines the stats in the side bar, and also which stats show in node/item comparisons
-- This may be user-customisable in the future


local displayStats = {
	{ stat = "ActiveMinionLimit", label = StatT("Active Minion Limit"), fmt = "d" },
	{ stat = "AverageHit", label = StatT("Average Hit"), fmt = ".1f", compPercent = true },
	{ stat = "PvpAverageHit", label = StatT("PvP Average Hit"), fmt = ".1f", compPercent = true, flag = "isPvP" },
	{ stat = "AverageDamage", label = StatT("Average Damage"), fmt = ".1f", compPercent = true, flag = "attack" },
	{ stat = "AverageDamage", label = StatT("Average Damage"), fmt = ".1f", compPercent = true, flag = "monsterExplode", condFunc = function(v,o) return o.HitChance ~= 100 end },
	{ stat = "AverageBurstDamage", label = StatT("Average Burst Damage"), fmt = ".1f", compPercent = true, condFunc = function(v,o) return o.AverageBurstHits and o.AverageBurstHits > 1 and v > 0 end },
	{ stat = "PvpAverageDamage", label = StatT("PvP Average Damage"), fmt = ".1f", compPercent = true, flag = "attackPvP" },
	{ stat = "Speed", label = StatT("Attack Rate"), fmt = ".2f", compPercent = true, flag = "attack", condFunc = function(v,o) return v > 0 and (o.TriggerTime or 0) == 0 end },
	{ stat = "Speed", label = StatT("Cast Rate"), fmt = ".2f", compPercent = true, flag = "spell", condFunc = function(v,o) return v > 0 and (o.TriggerTime or 0) == 0 end },
	{ stat = "Speed", label = StatT("Effective Trigger Rate"), fmt = ".2f", compPercent = true, condFunc = function(v,o) return (o.TriggerTime or 0) ~= 0 end },
	{ stat = "WarcryCastTime", label = StatT("Cast Time"), fmt = ".2fs", compPercent = true, lowerIsBetter = true, flag = "warcry" },
	{ stat = "HitSpeed", label = StatT("Hit Rate"), fmt = ".2f", compPercent = true, condFunc = function(v,o) return not o.TriggerTime end },
	{ stat = "HitTime", label = StatT("Channel Time"), fmt = ".2fs", compPercent = true, flag = "channelRelease", lowerIsBetter = true, condFunc = function(v,o) return not o.TriggerTime end },
	{ stat = "ChannelTimeToTrigger", label = StatT("Channel Time"), fmt = ".2fs", compPercent = true, lowerIsBetter = true, },
	{ stat = "TrapThrowingTime", label = StatT("Trap Throwing Time"), fmt = ".2fs", compPercent = true, lowerIsBetter = true, },
	{ stat = "TrapCooldown", label = StatT("Trap Cooldown"), fmt = ".3fs", lowerIsBetter = true },
	{ stat = "MineLayingTime", label = StatT("Mine Throwing Time"), fmt = ".2fs", compPercent = true, lowerIsBetter = true, },
	{ stat = "TrapThrowCount", label = StatT("Avg. Traps per Throw"), fmt = ".2f"},
	{ stat = "MineThrowCount", label = StatT("Avg. Mines per Throw"), fmt = ".2f"},
	{ stat = "TotemPlacementTime", label = StatT("Totem Placement Time"), fmt = ".2fs", compPercent = true, lowerIsBetter = true, condFunc = function(v,o) return not o.TriggerTime end },
	{ stat = "FiringRate", label = StatT("Firing Rate"), fmt = ".2f", compPercent = true, condFunc = function(v,o) return o.FiringRate end },
	{ stat = "ReloadTime", label = StatT("Reload Time"), fmt = ".2fs", compPercent = true, lowerIsBetter = true, condFunc = function(v,o) return o.ReloadTime end },
	{ stat = "PreEffectiveCritChance", label = StatT("Crit Chance"), fmt = ".2f%%", flag = "hit" },
	{ stat = "CritChance", label = StatT("Effective Crit Chance"), fmt = ".2f%%", flag = "hit", condFunc = function(v,o) return v ~= o.PreEffectiveCritChance end },
	{ stat = "CritForks", label = StatT("Crit Forks Chance"), fmt = ".2f%%", flag = "hit", condFunc = function(v,o) return (o.CritForks or 0) > 0 end },
	{ stat = "CritMultiplier", label = StatT("Crit Multiplier"), fmt = "d%%", pc = true, condFunc = function(v,o) return (o.CritChance or 0) > 0 end },
	{ stat = "HitChance", label = StatT("Hit Chance"), fmt = ".0f%%", flag = "attack" },
	{ stat = "HitChance", label = StatT("Hit Chance"), fmt = ".0f%%", condFunc = function(v,o) return o.enemyHasSpellBlock end },
	{ stat = "AccuracyHitChanceUncapped", label = StatT("Uncap. Hit Chance"), fmt = ".0f%%", flag = "attack", condFunc = function(v,o) if o.AccuracyHitChanceUncapped then return o.AccuracyHitChanceUncapped > 100 end end },
	{ stat = "TotalDPS", label = StatT("Hit DPS"), fmt = ".1f", compPercent = true, flag = "notAverage" },
	{ stat = "PvpTotalDPS", label = StatT("PvP Hit DPS"), fmt = ".1f", compPercent = true, flag = "notAveragePvP" },
	{ stat = "TotalDPS", label = StatT("Hit DPS"), fmt = ".1f", compPercent = true, flag = "showAverage", condFunc = function(v,o) return (o.TriggerTime or 0) ~= 0 end },
	{ stat = "TotalDot", label = StatT("DoT DPS"), fmt = ".1f", compPercent = true },
	{ stat = "WithDotDPS", label = StatT("Total DPS inc. DoT"), fmt = ".1f", compPercent = true, flag = "notAverage", condFunc = function(v,o) return v ~= o.TotalDPS and (o.PoisonDPS or 0) == 0 and (o.IgniteDPS or 0) == 0 and (o.ImpaleDPS or 0) == 0 and (o.BleedDPS or 0) == 0 end },
	{ stat = "BleedDPS", label = StatT("Bleed DPS"), fmt = ".1f", compPercent = true, warnFunc = function(v) return v >= data.misc.DotDpsCap and "Bleed DPS exceeds in game limit" end },
	{ stat = "CorruptingBloodDPS", label = StatT("Corrupting Blood DPS"), fmt = ".1f", compPercent = true, warnFunc = function(v,o) return v >= data.misc.DotDpsCap and "Corrupting Blood DPS exceeds in game limit" end },
	{ stat = "BleedDamage", label = StatT("Total Damage per Bleed"), fmt = ".1f", compPercent = true, flag = "showAverage" },
	{ stat = "WithBleedDPS", label = StatT("Total DPS inc. Bleed"), fmt = ".1f", compPercent = true, flag = "notAverage", condFunc = function(v,o) return v ~= o.TotalDPS and (o.TotalDot or 0) == 0 and (o.PoisonDPS or 0) == 0 and (o.ImpaleDPS or 0) == 0 and (o.IgniteDPS or 0) == 0 end },
	{ stat = "IgniteDPS", label = StatT("Ignite DPS"), fmt = ".1f", compPercent = true, warnFunc = function(v) return v >= data.misc.DotDpsCap and "Ignite DPS exceeds in game limit" end },
	{ stat = "IgniteDamage", label = StatT("Total Damage per Ignite"), fmt = ".1f", compPercent = true, flag = "showAverage" },
	{ stat = "BurningGroundDPS", label = StatT("Burning Ground DPS"), fmt = ".1f", compPercent = true, warnFunc = function(v,o) return v >= data.misc.DotDpsCap and "Burning Ground DPS exceeds in game limit" end },
	{ stat = "MirageBurningGroundDPS", label = StatT("Mirage Burning Ground DPS"), fmt = ".1f", compPercent = true, condFunc = function(v,o) return v ~= o.BurningGroundDPS end, warnFunc = function(v,o) return v >= data.misc.DotDpsCap and "Mirage Burning Ground DPS exceeds in game limit" end },
	{ stat = "WithIgniteDPS", label = StatT("Total DPS inc. Ignite"), fmt = ".1f", compPercent = true, flag = "notAverage", condFunc = function(v,o) return v ~= o.TotalDPS and (o.TotalDot or 0) == 0 and (o.PoisonDPS or 0) == 0 and (o.ImpaleDPS or 0) == 0 and (o.BleedDPS or 0) == 0 end },
	{ stat = "PoisonDPS", label = StatT("Poison DPS"), fmt = ".1f", compPercent = true, warnFunc = function(v) return v >= data.misc.DotDpsCap and "Poison DPS exceeds in game limit" end },
	{ stat = "CausticGroundDPS", label = StatT("Caustic Ground DPS"), fmt = ".1f", compPercent = true, warnFunc = function(v,o) return v >= data.misc.DotDpsCap and "Caustic Ground DPS exceeds in game limit" end },
	{ stat = "MirageCausticGroundDPS", label = StatT("Mirage Caustic Ground DPS"), fmt = ".1f", compPercent = true, condFunc = function(v,o) return v ~= o.CausticGroundDPS end, warnFunc = function(v,o) return v >= data.misc.DotDpsCap and "Mirage Caustic Ground DPS exceeds in game limit" end },
	{ stat = "PoisonDamage", label = StatT("Total Damage per Poison"), fmt = ".1f", compPercent = true, flag = "showAverage" },
	{ stat = "WithPoisonDPS", label = StatT("Total DPS inc. Poison"), fmt = ".1f", compPercent = true, flag = "notAverage", condFunc = function(v,o) return v ~= o.TotalDPS and (o.TotalDot or 0) == 0 and (o.IgniteDPS or 0) == 0 and (o.ImpaleDPS or 0) == 0 and (o.BleedDPS or 0) == 0 end },
	{ stat = "DecayDPS", label = StatT("Decay DPS"), fmt = ".1f", compPercent = true },
	{ stat = "TotalDotDPS", label = StatT("Total DoT DPS"), fmt = ".1f", compPercent = true, condFunc = function(v,o) return o.showTotalDotDPS or ( v ~= o.TotalDot and v ~= o.TotalPoisonDPS and v ~= o.CausticGroundDPS and v ~= (o.TotalIgniteDPS or o.IgniteDPS) and v ~= o.BurningGroundDPS and v ~= o.BleedDPS and v~= o.CorruptingBloodDPS and v ~= o.MirageCausticGroundDPS and v ~= o.MirageBurningGroundDPS) end, warnFunc = function(v) return v >= data.misc.DotDpsCap and "DoT DPS exceeds in game limit" end },
	{ stat = "ImpaleDPS", label = StatT("Impale Damage"), fmt = ".1f", compPercent = true, flag = "impale", flag = "showAverage" },
	{ stat = "WithImpaleDPS", label = StatT("Damage inc. Impale"), fmt = ".1f", compPercent = true, flag = "impale", flag = "showAverage", condFunc = function(v,o) return v ~= o.TotalDPS and (o.TotalDot or 0) == 0 and (o.IgniteDPS or 0) == 0 and (o.PoisonDPS or 0) == 0 and (o.BleedDPS or 0) == 0 end  },
	{ stat = "ImpaleDPS", label = StatT("Impale DPS"), fmt = ".1f", compPercent = true, flag = "impale", flag = "notAverage" },
	{ stat = "WithImpaleDPS", label = StatT("Total DPS inc. Impale"), fmt = ".1f", compPercent = true, flag = "impale", flag = "notAverage", condFunc = function(v,o) return v ~= o.TotalDPS and (o.TotalDot or 0) == 0 and (o.IgniteDPS or 0) == 0 and (o.PoisonDPS or 0) == 0 and (o.BleedDPS or 0) == 0 end },
	{ stat = "MirageDPS", label = StatT("Total Mirage DPS"), fmt = ".1f", compPercent = true, flag = "mirageArcher", condFunc = function(v,o) return v > 0 end },
	{ stat = "MirageDPS", label = StatT("Total Wisp DPS"), fmt = ".1f", compPercent = true, flag = "wisp", condFunc = function(v,o) return v > 0 end },
	{ stat = "CullingDPS", label = StatT("Culling DPS"), fmt = ".1f", compPercent = true, condFunc = function(v,o) return (o.CullingDPS or 0) > 0 end },
	{ stat = "ReservationDPS", label = StatT("Reservation DPS"), fmt = ".1f", compPercent = true, condFunc = function(v,o) return (o.ReservationDPS or 0) > 0 end },
	{ stat = "CombinedDPS", label = StatT("Combined DPS"), fmt = ".1f", compPercent = true, flag = "notAverage", condFunc = function(v,o) return v ~= ((o.TotalDPS or 0) + (o.TotalDot or 0)) and v ~= o.WithImpaleDPS and ( o.showTotalDotDPS or ( v ~= o.WithPoisonDPS and v ~= o.WithIgniteDPS and v ~= o.WithBleedDPS ) ) end },
	{ stat = "CombinedAvg", label = StatT("Combined Total Damage"), fmt = ".1f", compPercent = true, flag = "showAverage", condFunc = function(v,o) return (v ~= o.AverageDamage and (o.TotalDot or 0) == 0) and (v ~= o.WithPoisonDPS or v ~= o.WithIgniteDPS or v ~= o.WithBleedDPS) end },
	{ stat = "ExplodeChance", label = StatT("Total Explode Chance"), fmt = ".0f%%" },
	{ stat = "CombinedAvgToMonsterLife", label = StatT("Enemy Life Equivalent"), fmt = ".1f%%" },
	{ stat = "Cooldown", label = StatT("Skill Cooldown"), fmt = ".3fs", lowerIsBetter = true },
	{ stat = "SealCooldown", label = StatT("Seal Gain Frequency"), fmt = ".2fs", lowerIsBetter = true },
	{ stat = "SealMax", label = StatT("Max Number of Seals"), fmt = "d" },
	{ stat = "TimeMaxSeals", label = StatT("Time to Gain Max Seals"), fmt = ".2fs", lowerIsBetter = true },
	{ stat = "AreaOfEffectRadiusMetres", label = StatT("AoE Radius"), fmt = ".1fm" },
	{ stat = "BrandAttachmentRangeMetre", label = StatT("Attachment Range"), fmt = ".1fm", flag = "brand" },
	{ stat = "BrandTicks", label = StatT("Activations per Brand"), fmt = "d", flag = "brand" },
	{ stat = "ManaCost", label = StatT("Mana Cost"), fmt = "d", color = colorCodes.MANA, pool = "ManaUnreserved", compPercent = true, lowerIsBetter = true, condFunc = function(v,o) return o.ManaHasCost end },
	{ stat = "ManaPercentCost", label = StatT("Mana Cost"), fmt = "d%%", color = colorCodes.MANA, pool = "ManaUnreservedPercent", compPercent = true, lowerIsBetter = true, condFunc = function(v,o) return o.ManaPercentHasCost end },
	{ stat = "ManaPerSecondCost", label = StatT("Mana Cost per second"), fmt = ".2f", color = colorCodes.MANA, pool = "ManaUnreserved", compPercent = true, lowerIsBetter = true, condFunc = function(v,o) return o.ManaPerSecondHasCost end },
	{ stat = "ManaPercentPerSecondCost", label = StatT("Mana Cost per second"), fmt = ".2f%%", color = colorCodes.MANA, pool = "ManaUnreservedPercent", compPercent = true, lowerIsBetter = true, condFunc = function(v,o) return o.ManaPercentPerSecondHasCost end },
	{ stat = "LifeCost", label = StatT("Life Cost"), fmt = "d", color = colorCodes.LIFE, pool = "LifeUnreserved", compPercent = true, lowerIsBetter = true, condFunc = function(v,o) return o.LifeHasCost end },
	{ stat = "LifePercentCost", label = StatT("Life Cost"), fmt = "d%%", color = colorCodes.LIFE, pool = "LifeUnreservedPercent", compPercent = true, lowerIsBetter = true, condFunc = function(v,o) return o.LifePercentHasCost end },
	{ stat = "LifePerSecondCost", label = StatT("Life Cost per second"), fmt = ".2f", color = colorCodes.LIFE, pool = "LifeUnreserved", compPercent = true, lowerIsBetter = true, condFunc = function(v,o) return o.LifePerSecondHasCost end },
	{ stat = "LifePercentPerSecondCost", label = StatT("Life Cost per second"), fmt = ".2f%%", color = colorCodes.LIFE, pool = "LifeUnreservedPercent", compPercent = true, lowerIsBetter = true, condFunc = function(v,o) return o.LifePercentPerSecondHasCost end },
	{ stat = "ESCost", label = StatT("Energy Shield Cost"), fmt = "d", color = colorCodes.ES, pool = "EnergyShield", compPercent = true, lowerIsBetter = true, condFunc = function(v,o) return o.ESHasCost end },
	{ stat = "ESPerSecondCost", label = StatT("ES Cost per second"), fmt = ".2f", color = colorCodes.ES, pool = "EnergyShield", compPercent = true, lowerIsBetter = true, condFunc = function(v,o) return o.ESPerSecondHasCost end },
	{ stat = "ESPercentPerSecondCost", label = StatT("ES Cost per second"), fmt = ".2f%%", color = colorCodes.ES, compPercent = true, lowerIsBetter = true, condFunc = function(v,o) return o.ESPercentPerSecondHasCost end },
	{ stat = "RageCost", label = StatT("Rage Cost"), fmt = "d", color = colorCodes.RAGE, pool = "Rage", compPercent = true, lowerIsBetter = true, condFunc = function(v,o) return o.RageHasCost end },
	{ stat = "RagePerSecondCost", label = StatT("Rage Cost per second"), fmt = ".2f", color = colorCodes.RAGE, pool = "Rage", compPercent = true, lowerIsBetter = true, condFunc = function(v,o) return o.RagePerSecondHasCost end },
	{ stat = "SoulCost", label = StatT("Soul Cost"), fmt = "d", color = colorCodes.RAGE, pool = "Soul", compPercent = true, lowerIsBetter = true, condFunc = function(v,o) return o.SoulHasCost end },
	{ },
	{ stat = "Str", label = StatT("Strength"), color = colorCodes.STRENGTH, fmt = "d" },
	{ stat = "ReqStr", label = StatT("Strength Required"), color = colorCodes.STRENGTH, fmt = "d", lowerIsBetter = true, condFunc = function(v,o) return v > o.Str end, warnFunc = function(v,o) return "You do not meet the Strength requirement of " .. (o.ReqStrItem.source == "Item" and o.ReqStrItem.sourceItem.name or o.ReqStrItem.source == "Gem" and o.ReqStrItem.sourceGem.nameSpec) end },
	{ stat = "Dex", label = StatT("Dexterity"), color = colorCodes.DEXTERITY, fmt = "d" },
	{ stat = "ReqDex", label = StatT("Dexterity Required"), color = colorCodes.DEXTERITY, fmt = "d", lowerIsBetter = true, condFunc = function(v,o) return v > o.Dex end, warnFunc = function(v,o) return "You do not meet the Dexterity requirement of " .. (o.ReqDexItem.source == "Item" and o.ReqDexItem.sourceItem.name or o.ReqDexItem.source == "Gem" and o.ReqDexItem.sourceGem.nameSpec) end },
	{ stat = "Int", label = StatT("Intelligence"), color = colorCodes.INTELLIGENCE, fmt = "d" },
	{ stat = "ReqInt", label = StatT("Intelligence Required"), color = colorCodes.INTELLIGENCE, fmt = "d", lowerIsBetter = true, condFunc = function(v,o) return v > o.Int end, warnFunc = function(v,o) return "You do not meet the Intelligence requirement of " .. (o.ReqIntItem.source == "Item" and o.ReqIntItem.sourceItem.name or o.ReqIntItem.source == "Gem" and o.ReqIntItem.sourceGem.nameSpec) end },
	{ },
	{ stat = "Devotion", label = StatT("Devotion"), color = colorCodes.RARE, fmt = "d" },
	{ },
	{ stat = "TotalEHP", label = StatT("Effective Hit Pool"), fmt = ".0f", compPercent = true },
	{ stat = "PvPTotalTakenHit", label = StatT("PvP Hit Taken"), fmt = ".1f", flag = "isPvP", lowerIsBetter = true },
	{ stat = "PhysicalMaximumHitTaken", label = StatT("Phys Max Hit"), fmt = ".0f", color = colorCodes.PHYS, compPercent = true,  },
	{ stat = "LightningMaximumHitTaken", label = StatT("Elemental Max Hit"), fmt = ".0f", color = colorCodes.LIGHTNING, compPercent = true, condFunc = function(v,o) return o.LightningMaximumHitTaken == o.ColdMaximumHitTaken and o.LightningMaximumHitTaken == o.FireMaximumHitTaken end },
	{ stat = "FireMaximumHitTaken", label = StatT("Fire Max Hit"), fmt = ".0f", color = colorCodes.FIRE, compPercent = true, condFunc = function(v,o) return o.LightningMaximumHitTaken ~= o.ColdMaximumHitTaken or o.LightningMaximumHitTaken ~= o.FireMaximumHitTaken end },
	{ stat = "ColdMaximumHitTaken", label = StatT("Cold Max Hit"), fmt = ".0f", color = colorCodes.COLD, compPercent = true, condFunc = function(v,o) return o.LightningMaximumHitTaken ~= o.ColdMaximumHitTaken or o.LightningMaximumHitTaken ~= o.FireMaximumHitTaken end },
	{ stat = "LightningMaximumHitTaken", label = StatT("Lightning Max Hit"), fmt = ".0f", color = colorCodes.LIGHTNING, compPercent = true, condFunc = function(v,o) return o.LightningMaximumHitTaken ~= o.ColdMaximumHitTaken or o.LightningMaximumHitTaken ~= o.FireMaximumHitTaken end },
	{ stat = "ChaosMaximumHitTaken", label = StatT("Chaos Max Hit"), fmt = ".0f", color = colorCodes.CHAOS, compPercent = true },
	{ },
	{ stat = "MainHand", childStat = "Accuracy", label = StatT("MH Accuracy"), fmt = "d", condFunc = function(v,o) return o.PreciseTechnique end, warnFunc = function(v,o) return v < o.Life and "You do not have enough Accuracy for Precise Technique" end, warnColor = true },
	{ stat = "OffHand", childStat = "Accuracy", label = StatT("OH Accuracy"), fmt = "d", condFunc = function(v,o) return o.PreciseTechnique end, warnFunc = function(v,o) return v < o.Life and "You do not have enough Accuracy for Precise Technique" end, warnColor = true },
	{ },
	{ stat = "Darkness", label = StatT("Total Darkness"), fmt = "d", color = colorCodes.CHAOS},
	{ stat = "ReservedDarkness", label = StatT("Reserved Darkness"), fmt ="d", color = colorCodes.CHAOS},
	{ },
	{ stat = "Life", label = StatT("Total Life"), fmt = "d", color = colorCodes.LIFE, compPercent = true },
	{ stat = "Spec:LifeInc", label = "%Inc Life", fmt = "d%%", color = colorCodes.LIFE, condFunc = function(v,o) return v > 0 and o.Life > 1 end },
	{ stat = "LifeUnreserved", label = StatT("Unreserved Life"), fmt = "d", color = colorCodes.LIFE, condFunc = function(v,o) return v < o.Life end, compPercent = true, warnFunc = function(v) return v <= 0 and "Your unreserved Life is below 1" end },
	{ stat = "LifeRecoverable", label = StatT("Life Recoverable"), fmt = "d", color = colorCodes.LIFE, condFunc = function(v,o) return v < o.LifeUnreserved end, },
	{ stat = "LifeUnreservedPercent", label = StatT("Unreserved Life"), fmt = "d%%", color = colorCodes.LIFE, condFunc = function(v,o) return v < 100 end },
	{ stat = "LifeRegenRecovery", label = StatT("Life Regen"), fmt = ".1f", color = colorCodes.LIFE, condFunc = function(v,o) return o.LifeRecovery <= 0 and o.LifeRegenRecovery ~= 0 end },
	{ stat = "LifeRegenRecovery", label = StatT("Life Recovery"), fmt = ".1f", color = colorCodes.LIFE, condFunc = function(v,o) return o.LifeRecovery > 0 and o.LifeRegenRecovery ~= 0 end },
	{ stat = "LifeLeechGainRate", label = StatT("Life Leech/On Hit Rate"), fmt = ".1f", color = colorCodes.LIFE, compPercent = true },
	{ stat = "LifeLeechGainPerHit", label = StatT("Life Leech/Gain per Hit"), fmt = ".1f", color = colorCodes.LIFE, compPercent = true },
	{ },
	{ stat = "Mana", label = StatT("Total Mana"), fmt = "d", color = colorCodes.MANA, compPercent = true },
	{ stat = "Spec:ManaInc", label = "%Inc Mana from Tree", color = colorCodes.MANA, fmt = "d%%" },
	{ stat = "ManaUnreserved", label = StatT("Unreserved Mana"), fmt = "d", color = colorCodes.MANA, condFunc = function(v,o) return v < o.Mana end, compPercent = true, warnFunc = function(v) return v < 0 and "Your unreserved Mana is negative" end },
	{ stat = "ManaUnreservedPercent", label = StatT("Unreserved Mana"), fmt = "d%%", color = colorCodes.MANA, condFunc = function(v,o) return v < 100 end },
	{ stat = "ManaRegenRecovery", label = StatT("Mana Regen"), fmt = ".1f", color = colorCodes.MANA, condFunc = function(v,o) return o.ManaRecovery <= 0 and o.ManaRegenRecovery ~= 0 end },
	{ stat = "ManaRegenRecovery", label = StatT("Mana Recovery"), fmt = ".1f", color = colorCodes.MANA, condFunc = function(v,o) return o.ManaRecovery > 0 and o.ManaRegenRecovery ~= 0 end },
	{ stat = "ManaLeechGainRate", label = StatT("Mana Leech/On Hit Rate"), fmt = ".1f", color = colorCodes.MANA, compPercent = true },
	{ stat = "ManaLeechGainPerHit", label = StatT("Mana Leech/Gain per Hit"), fmt = ".1f", color = colorCodes.MANA, compPercent = true },
	{ },
	{ stat = "Spirit", label = StatT("Total Spirit"), fmt = "d", color = colorCodes.SPIRIT, compPercent = true },
	{ stat = "SpiritUnreserved", label = StatT("Unreserved Spirit"), fmt = "d", color = colorCodes.SPIRIT, condFunc = function(v,o) return v < o.Spirit end, compPercent = true, warnFunc = function(v) return v < 0 and "Your unreserved Spirit is negative" end },
	{ stat = "SpiritUnreservedPercent", label = StatT("Unreserved Spirit"), fmt = "d%%", color = colorCodes.SPIRIT, condFunc = function(v,o) return v < 100 end },
	{ },
	{ stat = "EnergyShield", label = StatT("Energy Shield"), fmt = "d", color = colorCodes.ES, compPercent = true },
	{ stat = "EnergyShieldRecoveryCap", label = StatT("Recoverable ES"), color = colorCodes.ES, fmt = "d", condFunc = function(v,o) return o.CappingES end },
	{ stat = "Spec:EnergyShieldInc", label = "%Inc ES from Tree", color = colorCodes.ES, fmt = "d%%" },
	{ stat = "EnergyShieldRegenRecovery", label = StatT("ES Regen"), color = colorCodes.ES, fmt = ".1f", condFunc = function(v,o) return o.EnergyShieldRecovery <= 0 and o.EnergyShieldRegenRecovery ~= 0 end },
	{ stat = "EnergyShieldRegenRecovery", label = StatT("ES Recovery"), color = colorCodes.ES, fmt = ".1f", condFunc = function(v,o) return o.EnergyShieldRecovery > 0 and o.EnergyShieldRegenRecovery ~= 0 end },
	{ stat = "EnergyShieldLeechGainRate", label = StatT("ES Leech/On Hit Rate"), color = colorCodes.ES, fmt = ".1f", compPercent = true },
	{ stat = "EnergyShieldLeechGainPerHit", label = StatT("ES Leech/Gain per Hit"), color = colorCodes.ES, fmt = ".1f", compPercent = true },
	{ },
	{ stat = "Rage", label = StatT("Rage"), fmt = "d", color = colorCodes.RAGE, compPercent = true },
	{ stat = "RageRegenRecovery", label = StatT("Rage Regen"), fmt = ".1f", color = colorCodes.RAGE, compPercent = true },
	{ },
	{ stat = "TotalBuildDegen", label = StatT("Total Degen"), fmt = ".1f", lowerIsBetter = true },
	{ stat = "TotalNetRegen", label = StatT("Total Net Recovery"), fmt = "+.1f" },
	{ stat = "NetLifeRegen", label = StatT("Net Life Recovery"), fmt = "+.1f", color = colorCodes.LIFE },
	{ stat = "NetManaRegen", label = StatT("Net Mana Recovery"), fmt = "+.1f", color = colorCodes.MANA },
	{ stat = "NetEnergyShieldRegen", label = StatT("Net ES Recovery"), fmt = "+.1f", color = colorCodes.ES },
	{ },
	{ stat = "Evasion", label = StatT("Evasion rating"), fmt = "d", color = colorCodes.EVASION, compPercent = true },
	{ stat = "Spec:EvasionInc", label = "%Inc Evasion from Tree", color = colorCodes.EVASION, fmt = "d%%" },
	{ stat = "MeleeEvadeChance", label = StatT("Evade Chance"), fmt = "d%%", color = colorCodes.EVASION, condFunc = function(v,o) return v > 0 and o.MeleeEvadeChance == o.ProjectileEvadeChance end },
	{ stat = "MeleeEvadeChance", label = StatT("Melee Evade Chance"), fmt = "d%%", color = colorCodes.EVASION, condFunc = function(v,o) return v > 0 and o.MeleeEvadeChance ~= o.ProjectileEvadeChance end },
	{ stat = "ProjectileEvadeChance", label = StatT("Projectile Evade Chance"), fmt = "d%%", color = colorCodes.EVASION, condFunc = function(v,o) return v > 0 and o.MeleeEvadeChance ~= o.ProjectileEvadeChance end },
	{ },
	{ stat = "Armour", label = StatT("Armour"), fmt = "d", compPercent = true },
	{ stat = "Spec:ArmourInc", label = "%Inc Armour from Tree", fmt = "d%%" },
	{ stat = "PhysicalDamageReduction", label = StatT("Phys. Damage Reduction"), fmt = "d%%", condFunc = function() return true end },
	{ },
	{ stat = "EffectiveBlockChance", label = StatT("Block Chance"), fmt = "d%%", overCapStat = "BlockChanceOverCap" },
	{ stat = "EffectiveSpellBlockChance", label = StatT("Spell Block Chance"), fmt = "d%%", overCapStat = "SpellBlockChanceOverCap" },
	{ stat = "AttackDodgeChance", label = StatT("Attack Dodge Chance"), fmt = "d%%", overCapStat = "AttackDodgeChanceOverCap" },
	{ stat = "SpellDodgeChance", label = StatT("Spell Dodge Chance"), fmt = "d%%", overCapStat = "SpellDodgeChanceOverCap" },
	{ stat = "EffectiveSpellSuppressionChance", label = StatT("Spell Suppression Chance"), fmt = "d%%", overCapStat = "SpellSuppressionChanceOverCap" },
	{ },
	{ stat = "FireResist", label = StatT("Fire Resistance"), fmt = "d%%", color = colorCodes.FIRE, condFunc = function() return true end, overCapStat = "FireResistOverCap"},
	{ stat = "FireResistOverCap", label = StatT("Fire Res. Over Max"), fmt = "d%%", hideStat = true },
	{ stat = "ColdResist", label = StatT("Cold Resistance"), fmt = "d%%", color = colorCodes.COLD, condFunc = function() return true end, overCapStat = "ColdResistOverCap" },
	{ stat = "ColdResistOverCap", label = StatT("Cold Res. Over Max"), fmt = "d%%", hideStat = true },
	{ stat = "LightningResist", label = StatT("Lightning Resistance"), fmt = "d%%", color = colorCodes.LIGHTNING, condFunc = function() return true end, overCapStat = "LightningResistOverCap" },
	{ stat = "LightningResistOverCap", label = StatT("Lightning Res. Over Max"), fmt = "d%%", hideStat = true },
	{ stat = "ChaosResist", label = StatT("Chaos Resistance"), fmt = "d%%", color = colorCodes.CHAOS, condFunc = function(v,o) return not o.ChaosInoculation end, overCapStat = "ChaosResistOverCap" },
	{ stat = "ChaosResistOverCap", label = StatT("Chaos Res. Over Max"), fmt = "d%%", hideStat = true },
	{ label = StatT("Chaos Resistance"), val = "Immune", labelStat = "ChaosResist", color = colorCodes.CHAOS, condFunc = function(o) return o.ChaosInoculation end },
	{ },
	{ stat = "EffectiveMovementSpeedMod", label = StatT("Movement Speed Modifier"), fmt = "+.1f%%", mod = true, condFunc = function() return true end },
	{ },
	{ stat = "PresenceRadiusMetres", label = StatT("Presence Radius"), fmt = ".1fm", compPercent = true },
	--[[ potentially useful mods
	{ stat = "QuantityMultiplier", label = StatT("Quantity Multiplier"), fmt = "+d%%" },
	{ stat = "StoredUses", label = StatT("Stored Uses"), fmt = "d" },
	{ stat = "Duration", label = StatT("Skill Duration"), fmt = ".2f", flag = "duration" },
	{ stat = "DurationSecondary", label = StatT("Secondary Duration"), fmt = ".2f", flag = "duration" },
	{ stat = "AuraDuration", label = StatT("Aura Duration"), fmt = ".2f" },
	{ stat = "ReserveDuration", label = StatT("Reserve Duration"), fmt = ".2f" },
	{ stat = "SoulGainPreventionDuration", label = StatT("Soul Gain Prevent."), fmt = ".2f" },
	{ stat = "SustainableTrauma", label = StatT("Sustainable Trauma"), fmt = "d" },
	{ stat = "ProjectileCount", label = StatT("Projectile Count"), fmt = "d", flag = "projectile" },
	{ stat = "PierceCountString", label = StatT("Pierce Count"), fmt = "d" },
	{ stat = "ForkCountString", label = StatT("Fork Count"), fmt = "d" },
	{ stat = "ChainMaxString", label = StatT("Max Chain Count"), fmt = "d" },
	{ stat = "SplitCountString", label = StatT("Proj, Split Count"), fmt = "d", flag = "projectile" },
	{ stat = "ProjectileSpeedMod", label = StatT("Proj. Speed Mod"), fmt = ".2f", flag = "projectile" },
	{ stat = "BounceCount", label = StatT("Bounces Count"), fmt = "d", flag = "bounce" },
	{ stat = "AuraEffectMod", label = StatT("Aura Effect Mod"), fmt = ".2f" },
	{ stat = "CurseEffectMod", label = StatT("Curse Effect Mod"), fmt = ".2f" },
	{ stat = "LootQuantity", label = StatT("Item Quantity"), fmt = "+d%%" },
	{ stat = "LootRarity", label = StatT("Item Rarity"), fmt = "+d%%" },
	--]]
	{ },
	{ stat = "FullDPS", label = StatT("Full DPS"), fmt = ".1f", color = colorCodes.CURRENCY, compPercent = true },
	{ stat = "FullDotDPS", label = StatT("Full Dot DPS"), fmt = ".1f", color = colorCodes.CURRENCY, compPercent = true, condFunc = function (v) return v >= data.misc.DotDpsCap end, warnFunc = function (v) return "Full Dot DPS exceeds in game limit" end },
	{ },
	{ stat = "SkillDPS", label = StatT("Skill DPS"), condFunc = function() return true end },
}
local minionDisplayStats = {
	{ stat = "AverageDamage", label = StatT("Average Damage"), fmt = ".1f", compPercent = true },
	{ stat = "Speed", label = StatT("Attack/Cast Rate"), fmt = ".2f", compPercent = true, condFunc = function(v,o) return v > 0 and (o.TriggerTime or 0) == 0 end },
	{ stat = "HitSpeed", label = StatT("Hit Rate"), fmt = ".2f" },
	{ stat = "Speed", label = StatT("Effective Trigger Rate"), fmt = ".2f", compPercent = true, condFunc = function(v,o) return (o.TriggerTime or 0) ~= 0 end },
	{ stat = "TotalDPS", label = StatT("Hit DPS"), fmt = ".1f", compPercent = true },
	{ stat = "TotalDot", label = StatT("DoT DPS"), fmt = ".1f", compPercent = true },
	{ stat = "WithDotDPS", label = StatT("Total DPS inc. DoT"), fmt = ".1f", compPercent = true, condFunc = function(v,o) return v ~= o.TotalDPS and (o.PoisonDPS or 0) == 0 and (o.IgniteDPS or 0) == 0 and (o.ImpaleDPS or 0) == 0 and (o.BleedDPS or 0) == 0 end },
	{ stat = "BleedDPS", label = StatT("Bleed DPS"), fmt = ".1f", compPercent = true, warnFunc = function(v) return v >= data.misc.DotDpsCap and "Minion Bleed DPS exceeds in game limit" end },
	{ stat = "WithBleedDPS", label = StatT("Total DPS inc. Bleed"), fmt = ".1f", compPercent = true, condFunc = function(v,o) return v ~= o.TotalDPS and (o.TotalDot or 0) == 0 and (o.PoisonDPS or 0) == 0 and (o.ImpaleDPS or 0) == 0 and (o.IgniteDPS or 0) == 0 end },
	{ stat = "IgniteDPS", label = StatT("Ignite DPS"), fmt = ".1f", compPercent = true, warnFunc = function(v) return v >= data.misc.DotDpsCap and "Minion Ignite DPS exceeds in game limit" end },
	{ stat = "WithIgniteDPS", label = StatT("Total DPS inc. Ignite"), fmt = ".1f", compPercent = true, condFunc = function(v,o) return v ~= o.TotalDPS and (o.TotalDot or 0) == 0 and (o.PoisonDPS or 0) == 0 and (o.ImpaleDPS or 0) == 0 and (o.BleedDPS or 0) == 0 end },
	{ stat = "PoisonDPS", label = StatT("Poison DPS"), fmt = ".1f", compPercent = true, warnFunc = function(v) return v >= data.misc.DotDpsCap and "Minion Poison dps exceeds in game limit" end },
	{ stat = "PoisonDamage", label = StatT("Total Damage per Poison"), fmt = ".1f", compPercent = true },
	{ stat = "WithPoisonDPS", label = StatT("Total DPS inc. Poison"), fmt = ".1f", compPercent = true, condFunc = function(v,o) return v ~= o.TotalDPS and (o.TotalDot or 0) == 0 and (o.IgniteDPS or 0) == 0 and (o.ImpaleDPS or 0) == 0 and (o.BleedDPS or 0) == 0 end },
	{ stat = "DecayDPS", label = StatT("Decay DPS"), fmt = ".1f", compPercent = true },
	{ stat = "TotalDotDPS", label = StatT("Total DoT DPS"), fmt = ".1f", compPercent = true, condFunc = function(v,o) return v ~= o.TotalDot and v ~= o.ImpaleDPS and v ~= o.TotalPoisonDPS and v ~= (o.TotalIgniteDPS or o.IgniteDPS) and v ~= o.BleedDPS end, warnFunc = function(v) return v >= data.misc.DotDpsCap and "Minion DoT DPS exceeds in game limit" end },
	{ stat = "ImpaleDPS", label = StatT("Impale DPS"), fmt = ".1f", compPercent = true, flag = "impale" },
	{ stat = "WithImpaleDPS", label = StatT("Total DPS inc. Impale"), fmt = ".1f", compPercent = true, flag = "impale", condFunc = function(v,o) return v ~= o.TotalDPS and (o.TotalDot or 0) == 0 and (o.IgniteDPS or 0) == 0 and (o.PoisonDPS or 0) == 0 and (o.BleedDPS or 0) == 0 end },
	{ stat = "CullingDPS", label = StatT("Culling DPS"), fmt = ".1f", compPercent = true, condFunc = function(v,o) return (o.CullingDPS or 0) > 0 end },
	{ stat = "ReservationDPS", label = StatT("Reservation DPS"), fmt = ".1f", compPercent = true, condFunc = function(v,o) return (o.ReservationDPS or 0) > 0 end },
	{ stat = "CombinedDPS", label = StatT("Combined DPS"), fmt = ".1f", compPercent = true, condFunc = function(v,o) return v ~= ((o.TotalDPS or 0) + (o.TotalDot or 0)) and v ~= o.WithImpaleDPS and v ~= o.WithPoisonDPS and v ~= o.WithIgniteDPS and v ~= o.WithBleedDPS end},
	{ stat = "Cooldown", label = StatT("Skill Cooldown"), fmt = ".3fs", lowerIsBetter = true },
	{ stat = "Life", label = StatT("Total Life"), fmt = ".1f", color = colorCodes.LIFE, compPercent = true },
	{ stat = "LifeRegenRecovery", label = StatT("Life Recovery"), fmt = ".1f", color = colorCodes.LIFE },
	{ stat = "LifeLeechGainRate", label = StatT("Life Leech/On Hit Rate"), fmt = ".1f", color = colorCodes.LIFE, compPercent = true },
	{ stat = "EnergyShield", label = StatT("Energy Shield"), fmt = "d", color = colorCodes.ES, compPercent = true },
	{ stat = "EnergyShieldRegenRecovery", label = StatT("ES Recovery"), fmt = ".1f", color = colorCodes.ES },
	{ stat = "EnergyShieldLeechGainRate", label = StatT("ES Leech/On Hit Rate"), fmt = ".1f", color = colorCodes.ES, compPercent = true },
}
-- Extra stats saved to the xml if not already saved there, mostly for 3rd party tools
local extraSaveStats = {
	"PowerCharges",
	"PowerChargesMax",
	"FrenzyCharges",
	"FrenzyChargesMax",
	"EnduranceCharges",
	"EnduranceChargesMax",
	"ActiveTotemLimit",
	"ActiveMinionLimit",
}

return displayStats, minionDisplayStats, extraSaveStats
