-- Keywords dictionary from poe2db.tw/jp/
-- Auto-generated by tools/scrape_poe2db.py. Do not edit by hand;
-- if you need to override an entry, add it under src/Locale/ja_JP/_overrides/
-- (override merge step is run after scrape — see tools/apply_overrides.py).
return {
}
