-- Mod template patterns from poe2db.tw/jp/Modifiers.
-- Auto-generated by tools/scrape_poe2db.py.
-- Each entry's `en` field is a Lua pattern; `ja` may reference %1..%N
-- captures. ModFormat() in Locale.lua falls back to the original on miss.
return {
	patterns = {
		{ en = "^Cannot be Knocked Back$", ja = "ノックバックを受けることがない" },
		{ en = "^Cannot be Stunned$", ja = "スタンを受けることがない" },
		{ en = "^Found Items have (%d+)%% chance to drop Corrupted in Area$", ja = "エリアで見つかるアイテムは%1%の確率でコラプト状態でドロップする" },
		{ en = "^Area contains (%d+) additional pack of Corrupted Vaal Monsters$", ja = "エリアにはコラプト状態のヴァールモンスターが追加で%1パック出現する" },
		{ en = "^Vaal Vessel contains an additional Corrupted Unique Item with two Implicit Modifiers$", ja = "ヴァールの器は暗黙モッドを2個持つコラプト状態であのユニークアイテムが追加で1個入っている" },
		{ en = "^(%d+)%% increased Quantity of Items found in this Area$", ja = "このエリアで見つかるアイテムの数量が%1%増加する" },
		{ en = "^Can have up to 3 Crafted Modifiers$", ja = "クラフトモッドを最大3個まで持つことができる" },
		{ en = "^Cannot roll Attack Modifiers$", ja = "アタックモッドはロールされない" },
		{ en = "^Cannot roll Caster Modifiers$", ja = "キャスターモッドはロールされない" },
		{ en = "^With 4 Notables Allocated in Radius, When you Kill a Rare monster, you gain (%d+) of its Modifiers for 20 seconds$", ja = "範囲内でノータブルパッシブが4個割り当てられていれば、プレイヤーがレアモンスターを倒した時にそのモッドの内%1個をを20秒間獲得する" },
		{ en = "^Melee and Melee Weapon Type modifiers in Radius are Transformed to Bow Modifiers$", ja = "範囲内の近接モッドと近接武器モッドは弓モッドに変化する" },
		{ en = "^Maps found in your Maps are Corrupted with 8 Modifiers$", ja = "マップで見つかるマップはコラプト状態で8個モッドを持つ" },
		{ en = "^(%d+) uses remaining$", ja = "残り使用回数 %1回" },
		{ en = "^When a Character Kills an Empowered Rare Monster,$", ja = "キャラクターが強化したレアモンスターを倒した時に" },
		{ en = "^they gain its Modifiers for 20 seconds$", ja = "その敵は持っているモッドを20秒間付与する" },
		{ en = "^(%d+)%% increased chance for Abyssal monsters in Map to have Abyssal Modifiers$", ja = "マップのアビサルモンスターがアビサルモッドを持つ確率が%1%増加する" },
	},
}
