#!/usr/bin/env python3
"""Scrape poe2db.tw/jp/ navigation links and build EN→JP dictionaries.

Output: src/Locale/ja_JP/<Category>.lua  (one file per category)

Strategy:
    poe2db structures internal links as <a href="/jp/Slug_With_Underscores">日本語名</a>.
    Slugs are the canonical English identifiers (matching PoB's Data/ contents).
    Link text is the localized Japanese name.

Dependencies (system packages only):
    - python3-requests  (apt install python3-requests, already present)
    - stdlib only otherwise

Respects:
    - robots.txt allows /, no crawl-delay specified → we apply 1.0s self-imposed.
    - User-Agent identifies the project for poe2db operators.
"""
import argparse
import html as html_lib
import re
import sys
import time
from pathlib import Path
from urllib.parse import unquote

import requests

BASE = "https://poe2db.tw"
USER_AGENT = "PoB-PoE2-JP/0.1 (i18n; +github.com/Conso-me/PathOfBuilding-PoE2)"
DELAY = 1.0  # seconds between requests; raise if poe2db ops object
TIMEOUT = 30

# poe2db markup notes:
#   - Top-level nav links use class="dropdown-item" / "nav-link" → exclude.
#   - Items use class="whiteitem ItemSubclass" and *relative* hrefs.
#   - Gems use class="gemitem" / "gem_red|green|blue|white|purple|black".
#   - Uniques use class="uniqueitem".
# We match by class pattern so nav garbage is dropped automatically.

CATEGORIES = {
    "Skills": {
        "urls": [
            "/jp/Skill_Gems", "/jp/Support_Gems", "/jp/Spirit_Gems",
            "/jp/Lineage_Supports",
        ],
        "class_re": r"(?:gemitem|gem_red|gem_green|gem_blue|gem_white|gem_purple|gem_black)",
    },
    "Items": {
        "urls": [
            "/jp/Body_Armours", "/jp/Helmets", "/jp/Gloves", "/jp/Boots", "/jp/Belts",
            "/jp/Rings", "/jp/Amulets", "/jp/Bows", "/jp/Crossbows", "/jp/Wands",
            "/jp/Staves", "/jp/Sceptres", "/jp/Spears", "/jp/Flails", "/jp/Quivers",
            "/jp/Shields", "/jp/Focuses", "/jp/Bucklers", "/jp/Charms", "/jp/Flasks",
            "/jp/Jewels", "/jp/Tablets",
        ],
        "class_re": r"whiteitem",
    },
    "Uniques": {
        "urls": ["/jp/Uniques"],
        "class_re": r"uniqueitem",
    },
    "Keywords": {
        "urls": ["/jp/Keywords"],
        # Keywords page uses generic /jp/Slug pattern — fall back to plain href match.
        "class_re": None,
    },
    "Tree": {
        "urls": ["/jp/passive-skill-tree/", "/jp/Ascendancy_class"],
        "class_re": None,
    },
}

# Plain nav link: <a href="/jp/Slug">JP</a> (used when class_re is None)
PLAIN_LINK_RE = re.compile(
    r'<a\b(?![^>]*class="[^"]*(?:dropdown-item|nav-link)[^"]*")(?:[^>]*?\s)?href="/jp/([^"#?]+?)"[^>]*>(.*?)</a>',
    re.IGNORECASE | re.DOTALL,
)
TAG_RE = re.compile(r"<[^>]+>")
WS_RE = re.compile(r"\s+")
KANA_KANJI_RE = re.compile(r"[぀-ヿ一-鿿]")


def class_link_re(class_re: str) -> re.Pattern:
    """<a class="... {class_re} ..." href="(/jp/)?Slug">JP</a> — relative hrefs allowed."""
    return re.compile(
        rf'<a\b[^>]*?\sclass="[^"]*?{class_re}[^"]*?"[^>]*?\shref="(?:/jp/)?([^"#?/][^"#?]*?)"[^>]*>(.*?)</a>',
        re.IGNORECASE | re.DOTALL,
    )


def clean_text(raw: str) -> str:
    txt = TAG_RE.sub("", raw)
    txt = html_lib.unescape(txt)
    return WS_RE.sub(" ", txt).strip()


def slug_to_en(slug: str) -> str:
    # poe2db slugs can contain percent-encoded chars (e.g. "Companion%3A_%7B0%7D")
    return unquote(slug).replace("_", " ")


def fetch(path: str) -> str:
    url = f"{BASE}{path}"
    r = requests.get(url, headers={"User-Agent": USER_AGENT}, timeout=TIMEOUT)
    r.raise_for_status()
    return r.text


def scrape_pairs(path: str, skip_slugs: set[str], pattern: re.Pattern) -> dict[str, str]:
    """Extract EN slug → JA text pairs from one listing page using the given regex."""
    html = fetch(path)
    pairs: dict[str, str] = {}
    for slug, inner in pattern.findall(html):
        if "/" in slug:           # ignore deep sub-pages
            continue
        if slug in skip_slugs:    # ignore nav/category self-links
            continue
        en = slug_to_en(slug)
        ja = clean_text(inner)
        if not ja or ja == en:
            continue
        if not KANA_KANJI_RE.search(ja):   # no Japanese chars → likely garbage
            continue
        pairs.setdefault(en, ja)
    return pairs


def lua_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def write_lua_dict(out_path: Path, mapping: dict[str, str], header: str) -> None:
    lines = [
        f"-- {header}",
        "-- Auto-generated by tools/scrape_poe2db.py. Do not edit by hand;",
        "-- if you need to override an entry, add it under src/Locale/ja_JP/_overrides/",
        "-- (override merge step is run after scrape — see tools/apply_overrides.py).",
        "return {",
    ]
    for en in sorted(mapping):
        ja = mapping[en]
        lines.append(f'\t["{lua_escape(en)}"] = "{lua_escape(ja)}",')
    lines.append("}")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Scrape poe2db.tw/jp into Lua dictionaries.")
    parser.add_argument("--only", choices=list(CATEGORIES), default=None,
                        help="Scrape one category only (debug).")
    parser.add_argument("--out", default=None,
                        help="Output directory (default: ../src/Locale/ja_JP/ relative to this script).")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print stats without writing files.")
    args = parser.parse_args(argv)

    out_dir = Path(args.out) if args.out else Path(__file__).resolve().parent.parent / "src" / "Locale" / "ja_JP"
    out_dir.mkdir(parents=True, exist_ok=True)

    # Self-link slugs: the listing page slugs themselves (so we don't re-add them as entries)
    skip_slugs = set()
    for spec in CATEGORIES.values():
        for p in spec["urls"]:
            skip_slugs.add(p.removeprefix("/jp/").rstrip("/"))

    categories = {args.only: CATEGORIES[args.only]} if args.only else CATEGORIES

    total = 0
    for category, spec in categories.items():
        merged: dict[str, str] = {}
        pattern = class_link_re(spec["class_re"]) if spec["class_re"] else PLAIN_LINK_RE
        for path in spec["urls"]:
            print(f"  GET {path}", flush=True)
            try:
                merged.update(scrape_pairs(path, skip_slugs, pattern))
            except requests.HTTPError as e:
                print(f"    ! HTTP {e.response.status_code} — skipped", file=sys.stderr)
            except requests.RequestException as e:
                print(f"    ! request failed: {e}", file=sys.stderr)
            time.sleep(DELAY)
        out_path = out_dir / f"{category}.lua"
        if not args.dry_run:
            write_lua_dict(out_path, merged, f"{category} dictionary from poe2db.tw/jp/")
        print(f"  -> {out_path.name}: {len(merged)} entries"
              + (" (dry-run, not written)" if args.dry_run else ""))
        total += len(merged)

    print(f"\nDone. {total} entries total across {len(categories)} categor{'y' if len(categories) == 1 else 'ies'}.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
