-- JaText.lua: DrawImage-based Japanese text renderer for PoB.
--
-- SimpleGraphic's TGF font system is hardcoded to 128 ASCII glyphs.
-- This module bypasses it by loading JA.{size}.tga atlases and drawing
-- Japanese characters glyph-by-glyph via DrawImage.
--
-- Exposes:
--   JaText.installHook()       -- monkey-patches DrawString/DrawStringWidth
--   JaText.drawString(...)     -- same signature as DrawString
--   JaText.stringWidth(...)    -- same signature as DrawStringWidth

local JaText = {}

-- Load the pre-built glyph position table (generated by gen_ja_font.py)
local glyphMapErr, GLYPH_MAP = PLoadModule("Locale/ja_JP/GlyphMap")
if glyphMapErr then
	ConPrintf("[JaText] WARN: GlyphMap not found (%s); JA rendering disabled", tostring(glyphMapErr))
	GLYPH_MAP = nil
end

-- Atlas texture handles, keyed by size: { [14] = imgHandle, ... }
local atlasHandles = {}

-- Translation lookup. Wired by Launch.lua after Locale loads (we cannot import
-- Locale here because JaText loads first). Hook stays inert until populated.
JaText.localeGetMap = nil
JaText.locale = nil  -- exposes Locale.TokenizeNumbers / Locale.ApplyTokens

-- PoB color codes are caret-prefixed: "^N" (digit), "^^N" (also digit), or
-- "^xRRGGBB" (hex). They get concatenated outside translation calls
-- (e.g. "^7" .. "Language:"), so we peel them before T_MAP lookup and
-- re-attach after.
local function stripLeadingColor(s)
	local prefix, body = "", s
	while true do
		local p, rest = body:match("^(%^x%x%x%x%x%x%x)(.*)$")
		if not p then p, rest = body:match("^(%^%^%d)(.*)$") end
		if not p then p, rest = body:match("^(%^%d)(.*)$") end
		if not p then break end
		prefix = prefix .. p
		body = rest
	end
	return prefix, body
end

-- Strip all PoB color codes (leading + interior) for a coarse lossy lookup.
-- We use this as a last-ditch translation path: color positions don't survive
-- the round trip, but at least the user sees JA text instead of EN.
local function stripAllColors(s)
	return (s:gsub("%^x%x%x%x%x%x%x", ""):gsub("%^%^?%d", ""))
end

local function translate(s)
	if not JaText.localeGetMap then return s end
	local map = JaText.localeGetMap()
	if not map then return s end

	-- 1. Exact match (fastest path).
	local hit = map[s]
	if hit then return hit end

	-- 2. Leading color codes stripped, body looked up, prefix reattached.
	local prefix, body = stripLeadingColor(s)
	if body ~= s then
		hit = map[body]
		if hit then return prefix .. hit end
	end

	-- 3. All color codes stripped (handles interior ^xRRGGBB). Lossy on color.
	local naked = stripAllColors(s)
	if naked ~= "" and naked ~= s and naked ~= body then
		hit = map[naked]
		if hit then return hit end
	end

	-- 4. Numeric tokenization fallback: "+15 to Strength" → "{0} to Strength"
	-- looked up, then values reinserted into the JA template.
	if JaText.locale and JaText.locale.TokenizeNumbers then
		local probe = (naked ~= "" and naked) or body or s
		local tmpl, vals = JaText.locale.TokenizeNumbers(probe)
		if tmpl ~= probe and vals and #vals > 0 then
			hit = map[tmpl]
			if hit then return JaText.locale.ApplyTokens(hit, vals) end
		end
	end

	return s
end

-- Retrieve (and cache) atlas handle for the given pixel size.
-- NewImageHandle:Load() resolves relative paths from the exe directory (runtime/),
-- NOT from the Lua CWD (src/). So "SimpleGraphic/Fonts/JA.{size}.tga" is correct.
-- Probe candidate paths for the atlas (NewImageHandle:Load resolves from Lua CWD = src/).
local ATLAS_PATHS = {
	"../runtime/SimpleGraphic/Fonts/JA.%d.tga",   -- dev: running from repo, exe in runtime/
	"SimpleGraphic/Fonts/JA.%d.tga",              -- installed: running from install root
}

local function getAtlas(size)
	if atlasHandles[size] ~= nil then return atlasHandles[size] or nil end

	for _, fmt in ipairs(ATLAS_PATHS) do
		local path = string.format(fmt, size)
		local f = io.open(path, "rb")
		if f then
			f:close()
			local h = NewImageHandle()
			pcall(function() h:Load(path) end)
			local w, ht = h:ImageSize()
			if (w or 0) > 0 then
				atlasHandles[size] = h
				ConPrintf("[JaText] Loaded atlas %dpx: %s (%dx%d)", size, path, w, ht)
				return h
			end
		end
	end

	ConPrintf("[JaText] Atlas size %d not found (tried %d paths)", size, #ATLAS_PATHS)
	atlasHandles[size] = false
	return nil
end

-- True if codepoint is in a range requiring the JA atlas.
local function needsJA(cp)
	return (cp >= 0x3000 and cp <= 0x9FFF)   -- CJK + hiragana + katakana + kanji
		or (cp >= 0xFF01 and cp <= 0xFF9F)     -- fullwidth / halfwidth
end

-- Decode UTF-8 string into a list of codepoints.
local function toCodepoints(s)
	local cps = {}
	local i = 1
	local len = #s
	while i <= len do
		local b = s:byte(i)
		local cp, step
		if b < 0x80 then
			cp, step = b, 1
		elseif b < 0xC0 then
			cp, step = 0xFFFD, 1
		elseif b < 0xE0 then
			cp = ((b - 0xC0) * 64) + ((s:byte(i+1) or 0x80) - 0x80)
			step = 2
		elseif b < 0xF0 then
			cp = ((b - 0xE0) * 4096) + (((s:byte(i+1) or 0x80) - 0x80) * 64) + ((s:byte(i+2) or 0x80) - 0x80)
			step = 3
		else
			cp = ((b - 0xF0) * 262144) + (((s:byte(i+1) or 0x80) - 0x80) * 4096) + (((s:byte(i+2) or 0x80) - 0x80) * 64) + ((s:byte(i+3) or 0x80) - 0x80)
			step = 4
		end
		cps[#cps+1] = cp
		i = i + step
	end
	return cps
end

-- Build segments: [{type="ascii"|"cjk", text=string|cps}, ...]
local function segment(cps)
	local segs = {}
	local buf = {}
	local mode = nil
	for _, cp in ipairs(cps) do
		local want = needsJA(cp) and "cjk" or "ascii"
		if want ~= mode then
			if #buf > 0 then
				segs[#segs+1] = { type = mode, data = buf }
				buf = {}
			end
			mode = want
		end
		buf[#buf+1] = cp
	end
	if #buf > 0 then
		segs[#segs+1] = { type = mode, data = buf }
	end
	return segs
end

-- Encode codepoints back to UTF-8 string (for ASCII segments → DrawString)
local function cpsToUTF8(cps)
	local parts = {}
	for _, cp in ipairs(cps) do
		if cp < 0x80 then
			parts[#parts+1] = string.char(cp)
		elseif cp < 0x800 then
			parts[#parts+1] = string.char(0xC0 + math.floor(cp/64), 0x80 + (cp % 64))
		elseif cp < 0x10000 then
			parts[#parts+1] = string.char(0xE0 + math.floor(cp/4096), 0x80 + math.floor((cp%4096)/64), 0x80 + (cp%64))
		else
			parts[#parts+1] = string.char(0xF0 + math.floor(cp/262144), 0x80 + math.floor((cp%262144)/4096), 0x80 + math.floor((cp%4096)/64), 0x80 + (cp%64))
		end
	end
	return table.concat(parts)
end

-- Nearest size in the atlas (sizes available: 10 12 14 16 18 20 24 28 32)
local ATLAS_SIZES = {10, 12, 14, 16, 18, 20, 24, 28, 32}
local function nearestAtlasSize(h)
	local best, bestDelta = ATLAS_SIZES[1], math.abs(h - ATLAS_SIZES[1])
	for _, s in ipairs(ATLAS_SIZES) do
		local d = math.abs(h - s)
		if d < bestDelta then best, bestDelta = s, d end
	end
	return best
end

-- Compute the advance width of one CJK codepoint at the given atlas size.
local function cjkAdvance(cp, atlasSize)
	if not GLYPH_MAP then return atlasSize end
	local sizeData = GLYPH_MAP[atlasSize]
	if not sizeData then return atlasSize end
	local g = sizeData.g[cp]
	if not g then return atlasSize end
	return g[5]  -- adv_total
end

-- Total pixel width of a string using mixed rendering.
local _origDrawStringWidth
local function mixedWidth(height, font, text)
	if not GLYPH_MAP then
		return _origDrawStringWidth(height, font, text)
	end
	local cps = toCodepoints(text)
	local segs = segment(cps)
	local total = 0
	local atlasSize = nearestAtlasSize(height)
	for _, seg in ipairs(segs) do
		if seg.type == "ascii" then
			total = total + _origDrawStringWidth(height, font, cpsToUTF8(seg.data))
		else
			for _, cp in ipairs(seg.data) do
				total = total + cjkAdvance(cp, atlasSize)
			end
		end
	end
	return total
end

-- Draw a single CJK glyph at (x, y) with the given atlas.
local function drawCJKGlyph(cp, x, y, height, atlas, sizeData, atlasSize)
	if not atlas or not sizeData then return 0 end
	local g = sizeData.g[cp]
	if not g then return height end  -- fallback: skip with advance=height
	local ax, ay, w, xoff, adv = g[1], g[2], g[3], g[4], g[5]
	local aw, ah = sizeData.atlasW, sizeData.atlasH

	local renderW = w
	local renderH = height

	-- Use atlasSize for correct texture row height sampling
	local glyphH = atlasSize or height
	local tc_l = ax / aw
	local tc_t = ay / ah
	local tc_r = (ax + w) / aw
	local tc_b = (ay + glyphH) / ah

	DrawImage(atlas, x + xoff, y, renderW, renderH, tc_l, tc_t, tc_r, tc_b)
	return adv
end

-- Main draw function: replaces DrawString for mixed content.
local _origDrawString
local function mixedDraw(x, y, align, height, font, text)
	if not GLYPH_MAP then
		return _origDrawString(x, y, align, height, font, text)
	end

	local cps = toCodepoints(text)
	-- Quick check: if no CJK, fall through
	local hasCJK = false
	for _, cp in ipairs(cps) do
		if needsJA(cp) then hasCJK = true; break end
	end
	if not hasCJK then
		return _origDrawString(x, y, align, height, font, text)
	end

	local atlasSize = nearestAtlasSize(height)
	local atlas = getAtlas(atlasSize)
	local sizeData = GLYPH_MAP and GLYPH_MAP[atlasSize]
	local segs = segment(cps)

	-- Calculate start x based on alignment
	local startX = x
	if align == "CENTER" or align == "CENTER_X" or align == "RIGHT" then
		local totalW = mixedWidth(height, font, text)
		if align == "CENTER" or align == "CENTER_X" then
			startX = x - totalW / 2
		else
			startX = x - totalW
		end
	end

	-- Draw each segment
	local curX = startX
	for _, seg in ipairs(segs) do
		if seg.type == "ascii" then
			local s = cpsToUTF8(seg.data)
			_origDrawString(curX, y, "LEFT", height, font, s)
			curX = curX + _origDrawStringWidth(height, font, s)
		else
			for _, cp in ipairs(seg.data) do
				local adv = drawCJKGlyph(cp, curX, y, height, atlas, sizeData, atlasSize)
				curX = curX + adv
			end
		end
	end
end

-- Install monkey-patches on DrawString / DrawStringWidth globals.
function JaText.installHook()
	if not GLYPH_MAP then
		ConPrintf("[JaText] Skipping hook install: GlyphMap unavailable")
		return false
	end
	_origDrawString = DrawString
	_origDrawStringWidth = DrawStringWidth

	DrawString = function(x, y, align, height, font, text, ...)
		if type(text) ~= "string" then
			return _origDrawString(x, y, align, height, font, text, ...)
		end
		text = translate(text)
		return mixedDraw(x, y, align, height, font, text)
	end

	DrawStringWidth = function(height, font, text, ...)
		if type(text) ~= "string" then
			return _origDrawStringWidth(height, font, text, ...)
		end
		text = translate(text)
		return mixedWidth(height, font, text)
	end

	-- Pre-load atlases for common sizes to avoid per-frame lazy loading
	for _, sz in ipairs({14, 16, 18, 20}) do
		getAtlas(sz)
	end

	ConPrintf("[JaText] Installed. Atlas sizes preloaded: 14 16 18 20")
	return true
end

return JaText
